applications/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework import routers
from rest_framework.authtoken import views

from .views import EstablecimientoUniversitarioList, EstablecimientoNoUniversitarioList, \
    EstablecimientoProductivoList, CLAE2List, ProvinciaGeoJSONList, DepartamentoGeoJSONList, LetraList, \
    EstudioUniversitarioList, EstudioNoUniversitarioList, TipoGestionList, EmpleoList, TipoTituloList

router = routers.DefaultRouter()

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="API proyecto georreferenciación",
        default_version='v1',
        description="Georreferenciamiento de establecimientos educativos, \
            tanto universitarios como no universitarios, y establecimientos productivos",
    ),
    public=True,
    permission_classes=[permissions.AllowAny, ],
)

urlpatterns = [
    path('', include(router.urls)),
    path('provincias-geojson/', ProvinciaGeoJSONList.as_view(),
         name='provincias-geojson'),
    path('departamentos-geojson/', DepartamentoGeoJSONList.as_view(),
         name='departamentos-geojson'),
    path('establecimientos-universitarios/', EstablecimientoUniversitarioList.as_view(),
         name='establecimientos-universitarios-list'),
    path('establecimientos-no-universitarios/', EstablecimientoNoUniversitarioList.as_view(),
         name='establecimientos-no-universitarios-list'),
    path('establecimientos-productivos/', EstablecimientoProductivoList.as_view(),
         name='establecimientos-productivo-list'),
    path('letra/', LetraList.as_view(), name='letra-list'),
    path('clae2/', CLAE2List.as_view(), name='clae2-list'),
    path('estudio-universitario/', EstudioUniversitarioList.as_view(), name='estudio-universitario-list'),
    path('estudio-no-universitario/', EstudioNoUniversitarioList.as_view(), name='estudio-no-universitario-list'),
    path('tipo-gestion/', TipoGestionList.as_view(), name='tipo-gestion-list'),
    path('empleo/', EmpleoList.as_view(), name='empleo-list'),
    path('tipo-titulo/', TipoTituloList.as_view(), name='tipo-titulo-list'),
    path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('token-auth/', views.obtain_auth_token),
    path('doc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-doc'),
]

applications/establecimientos/urls.py
from django.urls import path

from .views import (UniversidadImportView, FacultadImportView, EstablecimientoUniversitarioImportView, RamaImportView,
                    TituloImportView,
                    AreaDeEstudioImportView, EstablecimientoNoUniversitarioImportView,
                    EstablecimientoProductivoImportView, LetraImportView, DimensionEmpresaImportView,
                    CLAE2ImportView, GestionImportView, TipoTituloImportView, EscuelaImportView, UnidadMedidaImportView,
                    EstudioUniversitarioImportView, EstudioNoUniversitarioImportView)

app_name = "establecimientos"

urlpatterns = [
    path('importar-universidad/', UniversidadImportView.as_view(), name='importar-universidad'),
    path('importar-facultad/', FacultadImportView.as_view(), name='importar-facultad'),
    path('importar-establecimiento-universitario/', EstablecimientoUniversitarioImportView.as_view(),
         name='importar-establecimiento-universitario'),
    path('importar-escuela/', EscuelaImportView.as_view(), name='importar-escuela'),
    path('importar-establecimiento-no-universitario/', EstablecimientoNoUniversitarioImportView.as_view(),
         name='importar-establecimiento-no-universitario'),
    path('importar-establecimiento-productivo/', EstablecimientoProductivoImportView.as_view(),
         name='importar-establecimiento-productivo'),
    path('importar-tipo-titulo/', TipoTituloImportView.as_view(), name='importar-tipo-titulo'),
    path('importar-titulo/', TituloImportView.as_view(), name='importar-titulo'),
    path('importar-gestion/', GestionImportView.as_view(), name='importar-gestion'),
    path('importar-unidad-medida/', UnidadMedidaImportView.as_view(), name='importar-unidad-medida'),
    path('importar-area-de-estudio/', AreaDeEstudioImportView.as_view(), name='importar-area-de-estudio'),
    path('importar-rama/', RamaImportView.as_view(), name='importar-rama'),
    path('importar-letra/', LetraImportView.as_view(), name='importar-letra'),
    path('importar-estudio-universitario/', EstudioUniversitarioImportView.as_view(),
         name='importar-estudios-universitarios'),
    path('importar-estudio-no-universitario/', EstudioNoUniversitarioImportView.as_view(),
         name='importar-estudios-no-universitarios'),
    path('importar-clae2/', CLAE2ImportView.as_view(), name='importar-clae2'),
    path('importar-dimension-empresa/', DimensionEmpresaImportView.as_view(), name='importar-dimension-empresa'),
]

applications/ubicaciones/urls.py
from django.urls import path

from applications.ubicaciones.views import SectorMayoritarioImportView, TasaEmpleoFormalImportView

app_name = 'ubicaciones'

urlpatterns = [
    path('importar-sectores-mayoritarios/', SectorMayoritarioImportView.as_view(),
         name='importar-sectores-mayoritarios'),
    path('importar-tasa-empleo-formal/', TasaEmpleoFormalImportView.as_view(),
         name='importar-tasa-empleo-formal'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout_view/', logout_view, name='logout_view'),
    path('register/', register, name='register'),
    path('register_button/', register_button, name='register_button'),
    path('change_password/', change_password, name='change_password'),
    path('api/v1/', include('applications.api.urls')),
    path('ubicaciones/', include('applications.ubicaciones.urls')),
    path('establecimientos/', include('applications.establecimientos.urls')),
]

templates/partials/btn_change_password.html
{% if user.is_authenticated %}
    <a href="{% url 'change_password' %}" class="btn btn-warning ms-3">Cambiar contraseña</a>
{% endif %}

templates/partials/btn_login.html
{% if not user.is_authenticated %}
    <a href="{% url 'login' %}" class="btn btn-primary ms-3">Iniciar sesión</a>
{% endif %}

templates/partials/btn_logout.html
{% if user.is_authenticated %}
    <a href="{% url 'logout_view' %}" class="btn btn-danger ms-3">Cerrar sesión</a>
{% endif %}

templates/partials/btn_register.html
{% if request.user.is_superuser %}
    <a href="{% url 'register_button' %}" class="btn btn-primary">Registrar usuario</a>
{% endif %}

templates/partials/dropdown_importar.html
{% if request.user.is_superuser %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            Importar
        </a>
        <ul class="dropdown-menu">
            <li><strong class="dropdown-header">Establecimientos</strong></li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-universidad' %}">Universidad</a>
            </li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-facultad' %}">Facultad</a>
            </li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'establecimientos:importar-establecimiento-universitario' %}">
                    Establecimiento universitario
                </a>
            </li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-escuela' %}">Escuela</a>
            </li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-establecimiento-no-universitario' %}">Establecimiento
                no universitario</a></li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-establecimiento-productivo' %}">Establecimiento
                productivo</a></li>
            <li>
                <hr class="dropdown-divider">
                <strong class="dropdown-header">Propiedades de establecimientos educativos</strong>
            </li>
            <li><a class="dropdown-item"
                   href="{% url 'establecimientos:importar-gestion' %}">Gestión</a>
            </li>
            <li>
                <hr class="dropdown-divider">
                <strong class="dropdown-header">Estudio</strong>
            </li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-tipo-titulo' %}">Tipo
                de
                título</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-titulo' %}">Título</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-rama' %}">Rama de
                estudio</a></li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-area-de-estudio' %}">Área
                de estudio</a></li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-unidad-medida' %}">Unidad
                de medida</a></li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'establecimientos:importar-estudios-universitarios' %}">
                    Estudios universitarios
                </a>
            </li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'establecimientos:importar-estudios-no-universitarios' %}">
                    Estudios no universitarios
                </a>
            </li>
            <li>
                <hr class="dropdown-divider">
                <strong class="dropdown-header">Clasificadores de Actividad Económica</strong>
            </li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-letra' %}">Letra</a>
            </li>
            <li><a class="dropdown-item" href="{% url 'establecimientos:importar-clae2' %}">CLAE2</a>
            </li>
            <li>
                <hr class="dropdown-divider">
                <strong class="dropdown-header">Propiedades de establecimientos productivos</strong>
            </li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'establecimientos:importar-dimension-empresa' %}">
                    Tamaño de la empresa
                </a>
            </li>
            <li>
                <hr class="dropdown-divider">
                <strong class="dropdown-header">Propiedades de ubicaciones</strong>
            </li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'ubicaciones:importar-sectores-mayoritarios' %}">
                    Sectores mayoritarios
                </a>
            </li>
        </ul>
    </li>
{% endif %}

templates/partials/navbar.html
<nav class="navbar header bg-dark border-bottom border-body navbar-expand-lg bg-body-dark" data-bs-theme="dark">
    <div class="container">
        <span class="navbar-brand mb-0 h1">Mapa OEI</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:schema-doc' %}">API</a>
                </li>
                {% include 'partials/dropdown_importar.html' %}
            </ul>
        </div>
        {% include 'partials/btn_login.html' %}
        {% include 'partials/btn_register.html' %}
        {% include 'partials/btn_change_password.html' %}
        {% include 'partials/btn_logout.html' %}
    </div>
</nav>